/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoad;

import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author albertonieto
 */
public class GestionPiezas extends javax.swing.JFrame {

    /**
     * Creates new form GestionPiezas
     */
    DatosConexionBD datosConexion = null;

    public GestionPiezas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        botLimpiarPieza = new javax.swing.JButton();
        botInsertarPieza = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botEliminarPieza = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botModificarPieza = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        botInicioPieza = new javax.swing.JButton();
        botAtrasPieza = new javax.swing.JButton();
        botAdelantePieza = new javax.swing.JButton();
        botFinalPieza = new javax.swing.JButton();
        botCargarPieza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("CODIGO DE PIEZAS:");

        jLabel4.setText("NOMBRE:");

        jLabel5.setText("PRECIO:");

        jLabel6.setText("DESCRIPCIÓN:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        botLimpiarPieza.setText("LIMPIAR");
        botLimpiarPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpiarPiezaActionPerformed(evt);
            }
        });

        botInsertarPieza.setText("INSERTAR");
        botInsertarPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInsertarPiezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botLimpiarPieza)
                .addGap(18, 18, 18)
                .addComponent(botInsertarPieza)
                .addGap(217, 217, 217))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botLimpiarPieza)
                    .addComponent(botInsertarPieza))
                .addGap(16, 16, 16))
        );

        jTabbedPane2.addTab("Gestion de Piezas", jPanel1);

        jLabel2.setBackground(new java.awt.Color(153, 51, 255));
        jLabel2.setText("LISTA DE PIEZAS");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel8.setText("CODIGO DE PIEZAS:");

        botEliminarPieza.setText("ELIMINAR");
        botEliminarPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEliminarPiezaActionPerformed(evt);
            }
        });

        jLabel9.setText("NOMBRE:");

        jLabel10.setText("PRECIO:");

        botModificarPieza.setText("MODIFICAR");
        botModificarPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botModificarPiezaActionPerformed(evt);
            }
        });

        jLabel11.setText("DESCRIPCIÓN:");

        jTextField8.setEditable(false);

        botInicioPieza.setText("<<");
        botInicioPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInicioPiezaActionPerformed(evt);
            }
        });

        botAtrasPieza.setText("<");
        botAtrasPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtrasPiezaActionPerformed(evt);
            }
        });

        botAdelantePieza.setText(">");
        botAdelantePieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdelantePiezaActionPerformed(evt);
            }
        });

        botFinalPieza.setText(">>");
        botFinalPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFinalPiezaActionPerformed(evt);
            }
        });

        botCargarPieza.setText("CARGAR PIEZAS");
        botCargarPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargarPiezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField8)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(botInicioPieza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botAtrasPieza)
                                .addGap(18, 18, 18)
                                .addComponent(botAdelantePieza)
                                .addGap(18, 18, 18)
                                .addComponent(botFinalPieza))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(botEliminarPieza)
                                .addGap(18, 18, 18)
                                .addComponent(botModificarPieza)
                                .addGap(50, 50, 50)))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botCargarPieza)
                        .addGap(207, 207, 207))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jLabel7)
                    .addContainerGap(550, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(botCargarPieza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botInicioPieza)
                    .addComponent(botAtrasPieza)
                    .addComponent(botAdelantePieza)
                    .addComponent(botFinalPieza))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botEliminarPieza)
                    .addComponent(botModificarPieza))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Listado de Piezas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane2)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane2)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int contador = 0;
    ResultSet resultado = null;
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void botLimpiarPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpiarPiezaActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_botLimpiarPiezaActionPerformed

    private void botInsertarPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInsertarPiezaActionPerformed

        //Comprobar que los campos esten repletos
        if (jTextField1.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduce el codigo de la pieza");
        } else if (jTextField1.getText().length() > 6) {
            JOptionPane.showMessageDialog(null, "El código no puede superar los 6 caracteres");
        } else if (jTextField2.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduce el nombre de la pieza");
        } else if (jTextField2.getText().length() > 20) {
            JOptionPane.showMessageDialog(rootPane, "El nombre no puede superar los 20 caracteres");
        } else if (jTextField3.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduce el precio de la pieza");
        } else if (Float.parseFloat(jTextField3.getText()) < 0) {
            JOptionPane.showMessageDialog(rootPane, "El campo precio tiene que ser un numero mayor que 0");

        } else if (jTextField4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor introduce la descripción de la pieza");
        } else if (jTextField4.getText().length() > 40) {
            JOptionPane.showMessageDialog(rootPane, "El campo descripcion no puede superar los 40 caracteres");
        } else {
            //Llamar a la funcion que haga la insercion

            datosConexion = new DatosConexionBD();

            Connection con = null;
            try {
                //Abrimos la conexion
                con = DriverManager.getConnection(datosConexion.getCONNECTION_SCHEMA(), datosConexion.getUSERNAME(), datosConexion.getPASSWORD());

                //Llamar al procedimiento para insertar una pieza
                String sql = "{call insertar_pieza(?,?,?,?)}";
                CallableStatement insercion = con.prepareCall(sql);

                // Añadimos los valores a la sentencia
                insercion.setString(1, jTextField1.getText());
                insercion.setString(2, jTextField2.getText());
                insercion.setString(3, jTextField3.getText());
                insercion.setString(4, jTextField4.getText());

                int ok = insercion.executeUpdate();

                if (ok != 0) {

                    JOptionPane.showMessageDialog(null, "pieza añadida a la BD");
                    insercion.close();
                    con.close();
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");

                } else {

                    JOptionPane.showMessageDialog(null, "Error al añadir la pieza a la BD");
                    insercion.close();
                    con.close();
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Ha sido imposible añadir la pieza " + e.getMessage());
                System.out.println("Error->" + e.getMessage());
            }

        }

    }//GEN-LAST:event_botInsertarPiezaActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void botEliminarPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEliminarPiezaActionPerformed

        //BOTON DE ELIMINAR
        if (jTextField8.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "No hay ninguna pieza cargada, por favor dale al boton de cargar o inserta una pieza!!");
        } else {
            //Llamar a la funcion que haga el borrado
            datosConexion = new DatosConexionBD();

            Connection con = null;
            try {
                //Abrimos la conexion
                con = DriverManager.getConnection(datosConexion.getCONNECTION_SCHEMA(), datosConexion.getUSERNAME(), datosConexion.getPASSWORD());

                //Llamar al procedimiento para insertar una pieza
                String sql = "{call eliminar_pieza(?)}";
                CallableStatement borrar = con.prepareCall(sql);

                // Añadimos los valores a la sentencia
                borrar.setString(1, jTextField8.getText());
                int ok = borrar.executeUpdate();

                if (ok != 0) {
                    JOptionPane.showMessageDialog(null, "Pieza  borrada");
                    borrar.close();
                    con.close();

                } else {

                    JOptionPane.showMessageDialog(null, "Error al eliminar la pieza de la BD");
                    borrar.close();
                    con.close();
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Ha sido imposible añadir la pieza " + e.getMessage());
                System.out.println("Error->" + e.getMessage());
            }

        }
        //Cargar las piezas para refrescar
        botCargarPieza.doClick();
    }//GEN-LAST:event_botEliminarPiezaActionPerformed

    private void botModificarPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botModificarPiezaActionPerformed

    //BOTON DE modificar
        if (jTextField8.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "No hay ninguna pieza cargada, por favor dale al boton de cargar o inserta una pieza!!");
        } else {
            //Llamar a la funcion que haga la modificacion
            datosConexion = new DatosConexionBD();

            Connection con = null;
            try {
                //Abrimos la conexion
                con = DriverManager.getConnection(datosConexion.getCONNECTION_SCHEMA(), datosConexion.getUSERNAME(), datosConexion.getPASSWORD());

                //Llamar al procedimiento para modificar una pieza
                String sql = "{call modificar_pieza(?,?,?,?)}";
                CallableStatement modificar = con.prepareCall(sql);

                // Añadimos los valores a la sentencia
                modificar.setString(1, jTextField8.getText());
                modificar.setString(2, jTextField5.getText());
                modificar.setString(3, jTextField6.getText());
                modificar.setString(4, jTextField7.getText());

                int ok = modificar.executeUpdate();

                if (ok != 0) {
                    JOptionPane.showMessageDialog(null, "Pieza  modificada");
                    modificar.close();
                    con.close();

                } else {

                    JOptionPane.showMessageDialog(null, "Error al modificar la Pieza de la BD");
                    modificar.close();
                    con.close();
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Ha sido imposible modificar la Pieza " + e.getMessage());
                System.out.println("Error->" + e.getMessage());
            }

        }
        //Cargar otra vez los proveedores
        botCargarPieza.doClick();

    }//GEN-LAST:event_botModificarPiezaActionPerformed

    private void botCargarPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargarPiezaActionPerformed

        //Boton de cargar piezas
        datosConexion = new DatosConexionBD();
        try {
            Class.forName(datosConexion.getFOR_NAME());

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Recuerda insertar el driver");
        }

        try {

            Connection con = DriverManager.getConnection(datosConexion.getCONNECTION_SCHEMA(), datosConexion.getUSERNAME(), datosConexion.getPASSWORD());

            Statement query = con.createStatement();
            String sql = "SELECT * FROM pieza ORDER BY codigo;";
            resultado = query.executeQuery(sql);

            if (resultado.next()) {
                System.out.println(resultado.getString(1));
                System.out.println(resultado.getString(2));

                this.jTextField8.setText(resultado.getString(1));
                this.jTextField5.setText(resultado.getString(2));
                this.jTextField6.setText(resultado.getString(3));
                this.jTextField7.setText(resultado.getString(4));
                contador = 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botCargarPiezaActionPerformed

    private void botInicioPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInicioPiezaActionPerformed

        // Ir a la primera posición
        if (resultado != null) {
            try {
                resultado.first();
                contador = resultado.getRow();
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("precio"));
                this.jTextField7.setText(resultado.getString("descripcion"));
            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cargue los datos para navegar entre ellos");
        }

    }//GEN-LAST:event_botInicioPiezaActionPerformed

    private void botAtrasPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtrasPiezaActionPerformed

        //boton de retroceder uno atras
        boolean primero = false;
        try {
            primero = resultado.isFirst();
        } catch (SQLException ex) {
            Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (primero) {
            JOptionPane.showMessageDialog(null, "Ya estás en el primero");
        } else {
            try {

                contador--;
                resultado.absolute(contador);
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("precio"));
                this.jTextField7.setText(resultado.getString("descripcion"));

            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botAtrasPiezaActionPerformed

    private void botAdelantePiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdelantePiezaActionPerformed
        // Boton de avanzar una posicion
        boolean ultimo = false;
        try {
            ultimo = resultado.isLast();
        } catch (SQLException ex) {
            Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (ultimo) {
            JOptionPane.showMessageDialog(null, "Ya estás en el último");
        } else {
            try {

                contador++;
                resultado.absolute(contador);
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("precio"));
                this.jTextField7.setText(resultado.getString("descripcion"));

            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botAdelantePiezaActionPerformed

    private void botFinalPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFinalPiezaActionPerformed
        // Boton de ir al final

        if (resultado != null) {
            try {
                resultado.last();
                contador = resultado.getRow();
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("precio"));
                this.jTextField7.setText(resultado.getString("descripcion"));
            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cargue los datos para navegar entre ellos");
        }

    }//GEN-LAST:event_botFinalPiezaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPiezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPiezas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAdelantePieza;
    private javax.swing.JButton botAtrasPieza;
    private javax.swing.JButton botCargarPieza;
    private javax.swing.JButton botEliminarPieza;
    private javax.swing.JButton botFinalPieza;
    private javax.swing.JButton botInicioPieza;
    private javax.swing.JButton botInsertarPieza;
    private javax.swing.JButton botLimpiarPieza;
    private javax.swing.JButton botModificarPieza;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
