/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoad;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author albertonieto
 */
public class GestionProveedores extends javax.swing.JFrame {

    /**
     * Creates new form GestionProveedores
     */
    
    DatosConexionBD datosConexion = null;
    public GestionProveedores() {
        initComponents();
        this.jLabelActualProveedor.setVisible(false);
        this.jLabelFinalProveedor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        botLimpiarProveedor = new javax.swing.JButton();
        botInsertarProveedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botEliminarProveedor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botModificarProveedor = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        botInicioProveedor = new javax.swing.JButton();
        botAtrasProveedor = new javax.swing.JButton();
        botAdelanteProveedor = new javax.swing.JButton();
        botFinalProveedor = new javax.swing.JButton();
        botCargarProveedores = new javax.swing.JButton();
        jLabelActualProveedor = new javax.swing.JLabel();
        jLabelFinalProveedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("CODIGO DE PROVEEDOR:");

        jLabel4.setText("NOMBRE:");

        jLabel5.setText("APELLIDOS:");

        jLabel6.setText("DIRECCIÓN:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        botLimpiarProveedor.setText("LIMPIAR");
        botLimpiarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimpiarProveedorActionPerformed(evt);
            }
        });

        botInsertarProveedor.setText("INSERTAR");
        botInsertarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInsertarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botLimpiarProveedor)
                .addGap(18, 18, 18)
                .addComponent(botInsertarProveedor)
                .addGap(217, 217, 217))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botLimpiarProveedor)
                    .addComponent(botInsertarProveedor))
                .addGap(16, 16, 16))
        );

        jTabbedPane2.addTab("Gestion de Proveedores", jPanel1);

        jLabel2.setBackground(new java.awt.Color(153, 51, 255));
        jLabel2.setText("LISTA DE PROVEEDORES");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel8.setText("CODIGO DE PROVEEDOR:");

        botEliminarProveedor.setText("ELIMINAR");
        botEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEliminarProveedorActionPerformed(evt);
            }
        });

        jLabel9.setText("NOMBRE:");

        jLabel10.setText("APELLIDOS:");

        botModificarProveedor.setText("MODIFICAR");
        botModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botModificarProveedorActionPerformed(evt);
            }
        });

        jLabel11.setText("DIRECCIÓN:");

        jTextField8.setEditable(false);

        botInicioProveedor.setText("<<");
        botInicioProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInicioProveedorActionPerformed(evt);
            }
        });

        botAtrasProveedor.setText("<");
        botAtrasProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtrasProveedorActionPerformed(evt);
            }
        });

        botAdelanteProveedor.setText(">");
        botAdelanteProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdelanteProveedorActionPerformed(evt);
            }
        });

        botFinalProveedor.setText(">>");
        botFinalProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFinalProveedorActionPerformed(evt);
            }
        });

        botCargarProveedores.setText("CARGAR PROVEEDORES");
        botCargarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCargarProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField8)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(242, 242, 242))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(botInicioProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botAtrasProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(botAdelanteProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(botFinalProveedor))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(botEliminarProveedor)
                                .addGap(18, 18, 18)
                                .addComponent(botModificarProveedor)
                                .addGap(50, 50, 50)))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botCargarProveedores)
                        .addGap(207, 207, 207))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jLabel7)
                    .addContainerGap(650, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(botCargarProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botInicioProveedor)
                    .addComponent(botAtrasProveedor)
                    .addComponent(botAdelanteProveedor)
                    .addComponent(botFinalProveedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botEliminarProveedor)
                    .addComponent(botModificarProveedor))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Listado de Proveedores", jPanel2);

        jLabelActualProveedor.setText("jLabel1");
        jLabelActualProveedor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));

        jLabelFinalProveedor.setText("jLabel12");
        jLabelFinalProveedor.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane2)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(jLabelActualProveedor)
                .addGap(18, 18, 18)
                .addComponent(jLabelFinalProveedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActualProveedor)
                    .addComponent(jLabelFinalProveedor))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Contador
    private int contador = 0;
    ResultSet resultado = null;

    private void botLimpiarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimpiarProveedorActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");

    }//GEN-LAST:event_botLimpiarProveedorActionPerformed

    private void botInsertarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInsertarProveedorActionPerformed

        //Boton de insertar nuevo proveedor
        //Comprobar que los text fields necesarios esten repletos
        if (jTextField1.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduce el codigo de proveedor");
        } else if (jTextField1.getText().length() > 6) {
            JOptionPane.showMessageDialog(null, "El código no puede superar los 6 caracteres");
        } else if (jTextField2.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduce el nombre de proveedor");
        } else if (jTextField2.getText().length() > 20) {
            JOptionPane.showMessageDialog(rootPane, "El nombre no puede superar los 20 caracteres");
        } else if (jTextField3.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor introduce el Apellido de proveedor");
        } else if (jTextField3.getText().length() > 30) {
            JOptionPane.showMessageDialog(rootPane, "El campo apellido no puede superar los 30 caracteres");
        } else if (jTextField4.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor introduce la dirección del proveedor");
        } else if (jTextField4.getText().length() > 40) {
            JOptionPane.showMessageDialog(rootPane, "El campo dirección no puede superar los 40 caracteres");
        } else {
            //Llamar a la funcion que haga la insercion

            datosConexion = new DatosConexionBD();

            Connection con = null;
            try {
                //Abrimos la conexion
                con = DriverManager.getConnection(datosConexion.getCONNECTION_SCHEMA(), datosConexion.getUSERNAME(), datosConexion.getPASSWORD());

                //Llamar al procedimiento para insertar un proveedor
                String sql = "{call insertar_proveedor(?,?,?,?)}";
                CallableStatement insercion = con.prepareCall(sql);

                // Añadimos los valores a la sentencia
                insercion.setString(1, jTextField1.getText());
                insercion.setString(2, jTextField2.getText());
                insercion.setString(3, jTextField3.getText());
                insercion.setString(4, jTextField4.getText());

                int ok = insercion.executeUpdate();

                if (ok != 0) {

                    JOptionPane.showMessageDialog(null, "Proveedor añadido a la BD");
                    insercion.close();
                    con.close();
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");

                } else {

                    JOptionPane.showMessageDialog(null, "Error al añadir al proveedor a la BD");
                    insercion.close();
                    con.close();
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Ha sido imposible añadir al proveedor " + e.getMessage());
                System.out.println("Error->" + e.getMessage());
            }

        }


    }//GEN-LAST:event_botInsertarProveedorActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void botEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEliminarProveedorActionPerformed

        //BOTON DE ELIMINAR
        //Mostrar ventana de seguro que......
        //Llamar a la funcion de eliminar

    }//GEN-LAST:event_botEliminarProveedorActionPerformed

    private void botModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botModificarProveedorActionPerformed

        //Modificamos el Proveedor cargado
        //comprobamos que los campos necesarios estan repletos
        //Llamamos a la funcion de modificar

    }//GEN-LAST:event_botModificarProveedorActionPerformed

    private void botCargarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCargarProveedoresActionPerformed

        //Boton de cargar proveedores
       datosConexion = new DatosConexionBD();
        try {
            Class.forName(datosConexion.getFOR_NAME());

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Recuerda insertar el driver");
        }

        try {
            Connection con = DriverManager.getConnection(datosConexion.getCONNECTION_SCHEMA(), datosConexion.getUSERNAME(), datosConexion.getPASSWORD());
            Statement query = con.createStatement();
            String sql = "SELECT * FROM proveedor ORDER BY codigo;";
            resultado = query.executeQuery(sql);

            if (resultado.next()) {
                System.out.println(resultado.getString(1));
                System.out.println(resultado.getString(2));

                this.jTextField8.setText(resultado.getString(1));
                this.jTextField5.setText(resultado.getString(2));
                this.jTextField6.setText(resultado.getString(3));
                this.jTextField7.setText(resultado.getString(4));
                contador = 1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botCargarProveedoresActionPerformed

    private void botInicioProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInicioProveedorActionPerformed
        // TODO add your handling code here:
        if (resultado != null) {
            try {
                resultado.first();
                contador = resultado.getRow();
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("apellidos"));
                this.jTextField7.setText(resultado.getString("direccion"));
            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cargue los datos para navegar entre ellos");
        }
    }//GEN-LAST:event_botInicioProveedorActionPerformed

    private void botFinalProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFinalProveedorActionPerformed
        // TODO add your handling code here:

        if (resultado != null) {
            try {
                resultado.last();
                contador = resultado.getRow();
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("apellidos"));
                this.jTextField7.setText(resultado.getString("direccion"));
            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cargue los datos para navegar entre ellos");
        }

    }//GEN-LAST:event_botFinalProveedorActionPerformed

    private void botAtrasProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtrasProveedorActionPerformed
        boolean primero = false;
        try {
            primero = resultado.isFirst();
        } catch (SQLException ex) {
            Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (primero) {
            JOptionPane.showMessageDialog(null, "Ya estás en el primero");
        } else {
            try {

                contador--;
                resultado.absolute(contador);
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("apellidos"));
                this.jTextField7.setText(resultado.getString("direccion"));

            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botAtrasProveedorActionPerformed

    private void botAdelanteProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdelanteProveedorActionPerformed
        // TODO add your handling code here:
        boolean ultimo = false;
        try {
            ultimo = resultado.isLast();
        } catch (SQLException ex) {
            Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (ultimo) {
            JOptionPane.showMessageDialog(null, "Ya estás en el último");
        } else {
            try {

                contador++;
                resultado.absolute(contador);
                this.jTextField8.setText(resultado.getString("codigo"));
                this.jTextField5.setText(resultado.getString("nombre"));
                this.jTextField6.setText(resultado.getString("apellidos"));
                this.jTextField7.setText(resultado.getString("direccion"));

            } catch (SQLException ex) {
                Logger.getLogger(GestionProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botAdelanteProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAdelanteProveedor;
    private javax.swing.JButton botAtrasProveedor;
    private javax.swing.JButton botCargarProveedores;
    private javax.swing.JButton botEliminarProveedor;
    private javax.swing.JButton botFinalProveedor;
    private javax.swing.JButton botInicioProveedor;
    private javax.swing.JButton botInsertarProveedor;
    private javax.swing.JButton botLimpiarProveedor;
    private javax.swing.JButton botModificarProveedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelActualProveedor;
    private javax.swing.JLabel jLabelFinalProveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
