/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoad;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lander
 */
public class VentanaGestionGlobal1 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionGlobal1
     */
    // Variables globales
    DatosConexionBD datosCon = new DatosConexionBD();
    Statement query = null;
    Connection con = null;
    ResultSet resul = null;
    String sql = "";

    public VentanaGestionGlobal1() throws SQLException {
        initComponents();
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        //jButton4.setEnabled(false);

        try {
            Class.forName(datosCon.getFOR_NAME());
            con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
            query = con.createStatement();
            sql = "Select codigo from proveedor";
            resul = query.executeQuery(sql);

            while (resul.next()) {
                jComboBox1.addItem(resul.getString("codigo"));
            }
            resul.close();
            query.close();
            con.close();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Introduzca el driver");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage().toString());
        }
        try {
            Class.forName(datosCon.getFOR_NAME());
            con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
            query = con.createStatement();
            sql = "Select codigo from pieza";
            resul = query.executeQuery(sql);

            while (resul.next()) {
                jComboBox2.addItem(resul.getString("codigo"));
            }
            resul.close();
            query.close();
            con.close();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Introduzca el driver");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la Base de datos");
            System.out.println(ex.getMessage().toString());
        }
        try {
            Class.forName(datosCon.getFOR_NAME());
            con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
            query = con.createStatement();
            sql = "Select codigo from proyecto";
            resul = query.executeQuery(sql);

            while (resul.next()) {
                jComboBox3.addItem(resul.getString("codigo"));
            }
            resul.close();
            query.close();
            con.close();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Introduzca el driver");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la Base de datos");
            System.out.println(ex.getMessage().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Relaciones Proveedores - Piezas - Proyectos");

        jLabel2.setText("Proveedor: ");

        jLabel3.setText("Pieza: ");

        jLabel4.setText("Proyecto: ");

        jLabel5.setText("Cantidad: ");

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4)
                                .addGap(126, 126, 126)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        //Cuando se elige un item del combobox1
        if (jComboBox1.getItemCount() > 1) {
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "Select * from proveedor where codigo ='" + jComboBox1.getSelectedItem() + "'";
                resul = query.executeQuery(sql);

                //Comentario
                if (resul.next()) {
                    jTextField1.setText(resul.getString("nombre"));
                    jTextField2.setText(resul.getString("apellidos"));
                    jTextField3.setText(resul.getString("direccion"));

                }
                resul.close();
                query.close();
                con.close();
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        //Cuando se elige un item del combobox2
        if (jComboBox2.getItemCount() > 1) {
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "Select * from pieza where codigo ='" + jComboBox2.getSelectedItem() + "'";
                resul = query.executeQuery(sql);

                if (resul.next()) {
                    jTextField4.setText(resul.getString("nombre"));
                    jTextField5.setText(resul.getString("precio"));
                    jTextField6.setText(resul.getString("descripcion"));

                }
                resul.close();
                query.close();
                con.close();
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
        }


    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged

        //Cuando se elige un item del combobox3
        if (jComboBox3.getItemCount() > 1) {
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "Select * from proyecto where codigo ='" + jComboBox3.getSelectedItem() + "'";
                resul = query.executeQuery(sql);

                if (resul.next()) {
                    jTextField7.setText(resul.getString("nombre"));
                    jTextField8.setText(resul.getString("ciudad"));

                }
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }

            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "select cantidad\n"
                        + "from gestion\n"
                        + "where cod_proveedor = '" + jComboBox1.getSelectedItem() + "'\n"
                        + "and cod_pieza = '" + jComboBox2.getSelectedItem() + "'\n"
                        + "and cod_proyecto = '" + jComboBox3.getSelectedItem() + "'";

                resul = query.executeQuery(sql);
                if (resul.next()) {

                    jTextField10.setText(String.valueOf(resul.getInt("cantidad")));
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(true);
                    //jButton4.setEnabled(true);
                    jButton1.setEnabled(false);

                } else {
                    jTextField10.setText("-");
                    jButton1.setEnabled(true);

                }
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
            try {
                resul.close();
                query.close();
                con.close();
            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            int valor = Integer.parseInt(jTextField10.getText());
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "insert into gestion values ('" + jComboBox1.getSelectedItem() + "','" + jComboBox2.getSelectedItem() + "','" + jComboBox3.getSelectedItem() + "'," + valor + ")";
                int tuplas = query.executeUpdate(sql);

                if (tuplas > 0) {
                    JOptionPane.showMessageDialog(null, "Dato guardado");
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(true);
                    //jButton4.setEnabled(true);
                }
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
            try {
                query.close();
                con.close();
            } catch (Exception e) {
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor no puede no ser un numérico.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Actualizamos la cantidad
        try {
            int valor = Integer.parseInt(jTextField10.getText());
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "update gestion set cantidad = "+valor+" where cod_proveedor = '"+jComboBox1.getSelectedItem()+"' and cod_pieza = '"+jComboBox2.getSelectedItem()+"' and cod_proyecto = '"+jComboBox3.getSelectedItem()+"'";
                int tuplas = query.executeUpdate(sql);

                if (tuplas > 0) {
                    JOptionPane.showMessageDialog(null, "Dato guardado");
                    jButton1.setEnabled(false);
                }
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
            try {
                query.close();
                con.close();
            } catch (Exception e) {
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor no puede no ser un numérico.");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Borramos de la tabla gestión
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "delete from gestion where cod_proveedor = '"+jComboBox1.getSelectedItem()+"' and cod_pieza = '"+jComboBox2.getSelectedItem()+"' and cod_proyecto = '"+jComboBox3.getSelectedItem()+"'";
                int tuplas = query.executeUpdate(sql);

                if (tuplas > 0) {
                    JOptionPane.showMessageDialog(null, "Dato borrado");
                    jButton1.setEnabled(false);
                    jTextField10.setText("-");
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(false);
                    jButton3.setEnabled(false);
                }
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                System.out.println(ex.getMessage().toString());
            }
            try {
                query.close();
                con.close();
            } catch (Exception e) {
            }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaGestionGlobal1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VentanaGestionGlobal1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
