/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoad;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author albertonieto
 */
public class VentGestionGlobal1 extends javax.swing.JFrame {

    /**
     * Creates new form VentGestionGlobal1
     */
    // Variables globales
    DatosConexionBD datosCon = new DatosConexionBD();
    Statement query = null;
    Connection con = null;
    ResultSet resul = null;
    String sql = "";

    public VentGestionGlobal1() {

        initComponents();
        // Clear
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
<<<<<<< HEAD
        /*
=======
>>>>>>> a53e75a95399a86cc4020931b9ef2a90e3dc0720
        try {
            Class.forName(datosCon.getFOR_NAME());
            con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
            query = con.createStatement();
            sql = "Select codigo from proveedor";
            resul = query.executeQuery(sql);

            while (resul.next()) {
                jComboBox1.addItem(resul.getString("codigo"));
            }
            resul.close();
            query.close();
            con.close();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Introduzca el driver");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la Base de datos");
<<<<<<< HEAD
            System.out.println(ex.getMessage().toString());
        }
         */
=======
        }

>>>>>>> a53e75a95399a86cc4020931b9ef2a90e3dc0720
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("RELACIONES PROVEEDORES - PIEZAS - PROYECTOS");

        jButton1.setText("Insertar");

        jButton2.setText("Modificar");

        jButton3.setText("Eliminar");

        jButton4.setText("Listado");

        jLabel2.setText("Proveedor");

        jLabel3.setText("Pieza");

        jLabel4.setText("Proyecto");

        jLabel5.setText("Cantidad:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
<<<<<<< HEAD
        
        try {
            // Rellenamos el otro combo con los datos de las piezas asociadas
            Class.forName(datosCon.getFOR_NAME());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentGestionGlobal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {   
            con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
        } catch (SQLException ex) {
            Logger.getLogger(VentGestionGlobal1.class.getName()).log(Level.SEVERE, null, ex);
        }
            sql = "SELECT cod_pieza FROM gestion where cod_proveedor ='" + jComboBox1.getSelectedItem().toString() + "'";
        try {
            resul = query.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(VentGestionGlobal1.class.getName()).log(Level.SEVERE, null, ex);
        }
                jComboBox2.removeAllItems();
        try {
            while (resul.next()) {
                jComboBox2.addItem(resul.getString("cod_pieza"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentGestionGlobal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (jComboBox2.getSelectedItem() != null) {
            try {
                query = con.createStatement();
                sql = "SELECT * from pieza where codigo = '" + jComboBox2.getSelectedItem().toString() + "'";
                resul = query.executeQuery(sql);
                if (resul.next()) {
                    jTextField2.setText(resul.getString("nombre") + String.valueOf(resul.getFloat("precio")) + resul.getString("descripcion"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la BD");
            }

        }
=======
        // TODO add your handling code here:
>>>>>>> a53e75a95399a86cc4020931b9ef2a90e3dc0720
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Acción cuando seleccionamos un código de proveedor
        // Mostramos los datos en el text
<<<<<<< HEAD
        if (jComboBox1.getItemCount() == 0) {
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                sql = "Select codigo from proveedor";
                resul = query.executeQuery(sql);

                while (resul.next()) {
                    jComboBox1.addItem(resul.getString("codigo"));
                }
                resul.close();
                query.close();
                con.close();
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la Base de datos");
                System.out.println(ex.getMessage().toString());
            }

        } else {
            try {
                Class.forName(datosCon.getFOR_NAME());
                con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
                query = con.createStatement();
                if (jComboBox1.getSelectedItem() != null) {
                    sql = "Select * from proveedor where codigo = '" + jComboBox1.getSelectedItem().toString() + "'";
                    resul = query.executeQuery(sql);
                    if (resul.next()) {

                        jTextField1.setText(resul.getString("nombre") + " " + resul.getString("apellidos") + " " + resul.getString("direccion"));

                    }
                    // Rellenamos el otro combo con los datos de las piezas asociadas
                    sql = "SELECT cod_pieza FROM gestion where cod_proveedor ='" + jComboBox1.getSelectedItem().toString() + "'";
                    resul = query.executeQuery(sql);
                    jComboBox2.removeAllItems();
                    while (resul.next()) {
                        jComboBox2.addItem(resul.getString("cod_pieza"));
                    }
                    //       sql = "SELECT * from pieza where codigo = '" + jComboBox2.getSelectedItem().toString() + "'";
                    //       resul = query.executeQuery(sql);
                    //       if (resul.next()) {
                    //          jTextField2.setText(resul.getString("nombre") + String.valueOf(resul.getFloat("precio")) + resul.getString("descripcion"));
                    //        }
                }
                query.close();
                resul.close();
                con.close();
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Introduzca el driver");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la Base de datos");
                System.out.println(ex.getMessage().toString());
            }

        }
=======
        try {
            Class.forName(datosCon.getFOR_NAME());
            con = DriverManager.getConnection(datosCon.getCONNECTION_SCHEMA(), datosCon.getUSERNAME(), datosCon.getPASSWORD());
            query = con.createStatement();
            if (jComboBox1.getSelectedItem() != null) {
                sql = "Select * from proveedor where codigo = "+jComboBox1.getSelectedItem().toString();
                System.out.println();
                //resul = query.executeQuery(sql);

                //if (resul.next()) {

                //    jTextField1.setText(resul.getString("nombre") + " " + resul.getString("apellidos") + " " + resul.getString("direccion"));

                //}
                //resul.close();
                //query.close();
                //con.close();
            }

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Introduzca el driver");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la Base de datos");
        }

>>>>>>> a53e75a95399a86cc4020931b9ef2a90e3dc0720
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentGestionGlobal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentGestionGlobal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
